import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,ScanSearch,Inbox,Library,Blocks,ShieldCheck,Settings,Menu,X,ArrowUpRight,UploadCloud,Check,Clock3,FileCheck2,ChevronDown,Search,SlidersHorizontal,Hash,UserRoundCheck,PanelLeftClose,PanelLeftOpen} from 'lucide-react';
import './styles.css';

type View='Overview'|'Evaluations'|'Intake'|'Rule library'|'Audit ledger'|'Review queue'|'Verification'|'Settings';
const rows=[
 {employer:'Acacia Manufacturing',period:'August 2026',deduct:'25 Aug 2026',bcea:'01 Sep 2026',pfa:'07 Sep 2026',delta:'6 days',status:'Timing exposure',reviewer:'Thandi M.'},
 {employer:'Umoya Logistics',period:'August 2026',deduct:'29 Aug 2026',bcea:'05 Sep 2026',pfa:'07 Sep 2026',delta:'2 days',status:'Timing exposure',reviewer:'Unassigned'},
 {employer:'Cape Meridian Services',period:'August 2026',deduct:'31 Aug 2026',bcea:'07 Sep 2026',pfa:'07 Sep 2026',delta:'0 days',status:'Within configured window',reviewer:'—'},
 {employer:'Karoo Industrial Group',period:'July 2026',deduct:'28 Jul 2026',bcea:'04 Aug 2026',pfa:'07 Aug 2026',delta:'3 days',status:'Timing exposure',reviewer:'Lerato N.'}
];
const ledger=[['000284','Evaluation completed','System','LAW-2.4.1','9d4a…e81c'],['000283','Review route created','Thandi M.','FLOW-1.8','3f2b…4c09'],['000282','Source file normalized','System','INGEST-3.2','e663…a11b'],['000281','Rule set activated','Sipho K.','LAW-2.4.1','0ae7…d902']];
const nav:[View,any][]=[['Overview',LayoutDashboard],['Evaluations',ScanSearch],['Intake',Inbox],['Rule library',Library],['Audit ledger',Blocks],['Review queue',UserRoundCheck]];

function App(){
 const [view,setView]=useState<View>('Overview'),[menu,setMenu]=useState(false),[compact,setCompact]=useState(false),[intake,setIntake]=useState(false),[detail,setDetail]=useState<any>(null),[verify,setVerify]=useState<'idle'|'running'|'done'>('idle'),[period,setPeriod]=useState('Aug 2026'),[stage,setStage]=useState(0);
 useEffect(()=>{if(verify==='running'){const t=setTimeout(()=>setVerify('done'),1500);return()=>clearTimeout(t)}},[verify]);
 useEffect(()=>{if(!intake&&!detail)return;const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector<HTMLElement>(detail?'.drawer':'.modal');const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')||[]).filter(el=>!el.hasAttribute('disabled'));const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setIntake(false);setDetail(null);setStage(0)}if(e.key==='Tab'){const items=focusable();if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};requestAnimationFrame(()=>focusable()[0]?.focus());document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);previous?.focus()}},[intake,detail]);
 const go=(v:View)=>{setView(v);setMenu(false);if(v==='Intake')setIntake(true)};
 return <div className="app">
  <aside className={`${menu?'open':''} ${compact?'compact':''}`}>
   <div className="brand"><span className="brandmark">N<span>●</span></span>{!compact&&<div><b>NOVA.</b><small>INTELLIGENCE</small></div>}<button className="icon collapse" onClick={()=>setCompact(!compact)}>{compact?<PanelLeftOpen/>:<PanelLeftClose/>}</button></div>
   {!compact&&<button className="tenant"><i>NA</i><span><b>Northstar Admin</b><small>Demo environment</small></span><ChevronDown/></button>}
   <nav aria-label="Primary navigation">{nav.map(([n,I])=><button key={n} className={view===n?'active':''} onClick={()=>go(n)} title={n}><I/>{!compact&&<span>{n}</span>}{n==='Review queue'&&!compact&&<em>03</em>}</button>)}</nav>
   <div className="aside-bottom"><button onClick={()=>go('Verification')}><ShieldCheck/>{!compact&&'Verification'}</button><button onClick={()=>go('Settings')}><Settings/>{!compact&&'Settings'}</button>{!compact&&<div className="operator"><div>TM</div><span><b>Thandi Mokoena</b><small>Compliance operator</small></span><i></i></div>}</div>
  </aside>
  <main>
   <header className="top"><button className="mobile-menu icon" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu/></button><div className="title-block"><span className="eyebrow">NOVA / LAWOS / <b>{view.toUpperCase()}</b></span><h1>{view==='Overview'?'Operational overview':view}</h1><p>{view==='Overview'?'Monitor configured deadlines, evidence and reviewer work from one controlled record.':'Deterministic facts, versioned rules and human decisions in one evidence trail.'}</p></div><div className="header-actions"><label className="period">Period <select value={period} onChange={e=>setPeriod(e.target.value)}><option>Aug 2026</option><option>Jul 2026</option><option>Q3 2026</option></select></label><button className="primary intake-button" onClick={()=>setIntake(true)}><UploadCloud/> <span className="desktop-label">Run intake</span><span className="mobile-label">Intake</span></button></div></header>
   <div className="statusline"><span><i className="blue"></i>Demo data</span><span><i className="blue"></i>Deterministic engine</span><span><ShieldCheck/> Ledger verified · 20 Sep 2026, 09:42 SAST</span></div>
   {view==='Overview'?<Overview period={period} open={setDetail}/>:view==='Evaluations'?<Evaluations open={setDetail}/>:view==='Rule library'?<Rules/>:view==='Audit ledger'||view==='Verification'?<Ledger verify={verify} setVerify={setVerify}/>:<Generic view={view}/>}
   <footer><span>Nova Intelligence · Showcase build</span><p>This interface reports configured deadline facts. It does not determine breach or predict regulatory action.</p><span>ZA / SAST</span></footer>
  </main>
  {menu&&<button className="scrim" onClick={()=>setMenu(false)} aria-label="Close menu"/>}
  {intake&&<Intake stage={stage} setStage={setStage} close={()=>{setIntake(false);setStage(0)}}/>}
  {detail&&<Detail item={detail} close={()=>setDetail(null)}/>} 
 </div>
}

function Overview({period,open}:{period:string,open:(x:any)=>void}){const count=period==='Jul 2026'?'1,174':'1,248';return <>
 <section className="metrics"><Metric label="Timing exposures" value={period==='Jul 2026'?'07':'12'} sub="4 require review" alert/><div className="metric-facts"><Metric label="Records evaluated" value={count} sub="100% deterministic"/><Metric label="Awaiting review" value="03" sub="Oldest 18 hours"/></div><div className="integrity"><div className="integrity-ring"><span>100%</span></div><div><span className="eyebrow">LEDGER INTEGRITY</span><b>Chain verified</b><small>284 events · head 9d4a…e81c</small></div></div></section>
 <section className="timeline panel"><div className="timeline-head"><div><span className="eyebrow">TEMPORAL ANALYSIS</span><h2>One deduction. Two clocks.</h2><p>Configured statutory clocks diverge on a single source fact.</p></div><div className="case-context"><span>Evaluation</span><b>EVAL-0826-0412</b><small>Acacia Manufacturing · August 2026</small></div></div>
  <div className="clock-grid"><div className="clock-main"><div className="legend"><span><i className="red"></i>BCEA configured clock</span><span><i className="blue"></i>PFA configured clock</span></div><div className="track"><div className="axis"></div><div className="band"><span>EXPOSURE WINDOW · 6 DAYS</span></div><Tick left="3%" date="25 AUG" label="Deduction recorded"/><Tick left="34%" date="31 AUG" label="Month end"/><Tick left="48%" date="01 SEP" label="BCEA due" red/><Tick left="91%" date="07 SEP" label="PFA due" blue/></div></div>
  <aside className="calculation"><span className="eyebrow">CALCULATION</span><div><small>BCEA input</small><b>25 Aug + 7 days</b><strong>01 Sep 2026</strong></div><div><small>PFA input</small><b>31 Aug + 7 days</b><strong>07 Sep 2026</strong></div><div className="divergence"><small>Configured divergence</small><strong>6 days</strong></div></aside></div>
  <div className="wedge"><div><span>FACTUAL TIMING EXPOSURE</span><p>Deadlines differ under the configured rules. Human review determines the appropriate response.</p></div><button onClick={()=>open(rows[0])}>Inspect evidence <ArrowUpRight/></button></div>
 </section>
 <div className="split"><section className="panel table-panel"><div className="section-head"><div><span className="eyebrow">02 / EXPOSURE REGISTER</span><h2>Configured timing facts</h2></div><button className="secondary">View all <ArrowUpRight/></button></div><DataTable data={rows.slice(0,period==='Jul 2026'?1:4)} open={open}/></section>
 <aside className="panel modules"><span className="eyebrow">SYSTEM MODULES</span><h2>Engine state</h2>{[['LawOS','Active','LAW-2.4.1'],['RiskOS','Scoped preview','RISK-0.3'],['AuditOS','Scoped','AUDIT-0.1']].map((x,i)=><div className="module" key={x[0]}><span className={'module-icon m'+i}>0{i+1}</span><div><b>{x[0]}</b><small>{x[1]}</small></div><code>{x[2]}</code></div>)}<div className="note"><ShieldCheck/><p><b>Reproducible by design</b>Every determination binds a rule version to an input hash.</p></div></aside></div>
 <section className="panel ledger-mini"><div className="section-head"><div><span className="eyebrow">03 / RECENT LEDGER ACTIVITY</span><h2>Immutable event trail</h2></div><span className="verified"><Check/> Chain verified</span></div><LedgerTable/></section></>}
function Metric(p:any){return <article className={'metric '+(p.alert?'alert':'')}><p>{p.label}</p><strong>{p.value}</strong><small>{p.sub}</small></article>}
function Tick({left,date,label,red,blue}:any){return <div className={'tick '+(red?'redtick ':'')+(blue?'bluetick':'')} style={{left}}><i></i><b>{date}</b><span>{label}</span></div>}
function DataTable({data,open}:{data:any[],open:(x:any)=>void}){return <><div className="table-wrap desktop-table"><table><thead><tr><th>Employer / period</th><th>Deduction</th><th>BCEA due</th><th>PFA due</th><th>Delta</th><th>Factual status</th><th>Reviewer</th></tr></thead><tbody>{data.map((r,i)=><tr key={i} tabIndex={0} onClick={()=>open(r)} onKeyDown={e=>e.key==='Enter'&&open(r)}><td><b>{r.employer}</b><small>{r.period}</small></td><td>{r.deduct}</td><td>{r.bcea}</td><td>{r.pfa}</td><td><b>{r.delta}</b></td><td><span className={r.delta==='0 days'?'tag ok':'tag'}>{r.status}</span></td><td>{r.reviewer}</td></tr>)}</tbody></table></div><div className="mobile-records">{data.map((r,i)=><button className="record-card" key={i} onClick={()=>open(r)}><span className="record-index">0{i+1}</span><div className="record-title"><b>{r.employer}</b><small>{r.period}</small></div><span className={r.delta==='0 days'?'tag ok':'tag'}>{r.status}</span><dl><div><dt>Deadlines</dt><dd>{r.bcea} / {r.pfa}</dd></div><div><dt>Delta</dt><dd>{r.delta}</dd></div><div><dt>Reviewer</dt><dd>{r.reviewer}</dd></div></dl><span className="inspect">Inspect evidence <ArrowUpRight/></span></button>)}</div></>}
function LedgerTable(){return <><div className="table-wrap desktop-table"><table><thead><tr><th>Sequence</th><th>Event</th><th>Actor</th><th>Rule version</th><th>Event hash</th></tr></thead><tbody>{ledger.map(r=><tr key={r[0]}>{r.map((c,i)=><td key={i}>{i===0?<b>#{c}</b>:i===4?<code>{c}</code>:c}</td>)}</tr>)}</tbody></table></div><div className="mobile-records ledger-records">{ledger.map(r=><article className="record-card" key={r[0]}><span className="record-index">#{r[0]}</span><div className="record-title"><b>{r[1]}</b><small>{r[2]}</small></div><span className="verified"><Check/> Verified</span><dl><div><dt>Rule version</dt><dd><code>{r[3]}</code></dd></div><div><dt>Event hash</dt><dd><code>{r[4]}</code></dd></div></dl></article>)}</div></>}
function Evaluations({open}:any){return <section className="panel page-panel"><div className="toolbar"><div className="search"><Search/><input placeholder="Search employer, hash, or evaluation ID"/></div><button className="secondary"><SlidersHorizontal/> Filters</button></div><div className="section-head"><div><span className="eyebrow">EVALUATION REGISTER / 1,248 RECORDS</span><h2>Reproducible determinations</h2></div></div><DataTable data={rows} open={open}/></section>}
function Rules(){return <section className="panel page-panel"><div className="section-head"><div><span className="eyebrow">CONFIGURATION / VERSION CONTROLLED</span><h2>Rule library</h2></div><button className="primary">New draft</button></div><div className="rule-list">{[['BCEA section 34A','Deduction-relative deadline','LAW-2.4.1','Active'],['Pension Funds Act section 13A','Month-end contribution deadline','LAW-2.4.1','Active'],['Source normalization','Date and employer field mapping','INGEST-3.2','Active']].map((r,i)=><article><span>0{i+1}</span><div><h3>{r[0]}</h3><p>{r[1]}</p></div><code>{r[2]}</code><b><i></i>{r[3]}</b><ArrowUpRight/></article>)}</div><p className="disclaimer">Configured demo values are pending primary-source confirmation. Published versions are immutable and rule changes are never applied retroactively.</p></section>}
function Ledger({verify,setVerify}:any){return <section className="panel page-panel"><div className="section-head"><div><span className="eyebrow">SHA-256 / HASH-CHAINED</span><h2>Audit ledger</h2></div><button className="primary" disabled={verify==='running'} onClick={()=>setVerify('running')}>{verify==='running'?<><span className="spinner"/> Verifying chain…</>:<><ShieldCheck/> Verify chain</>}</button></div>{verify==='done'&&<div className="verify-result"><Check/><p><b>Chain verified · 284 events</b>Genesis through head hash · completed locally using showcase data</p><code>HEAD 9d4a7f2c…e81c</code></div>}<LedgerTable/><div className="hash-chain"><div><Hash/><span>GENESIS<small>000001</small></span></div><i></i><div><Hash/><span>PREVIOUS HASH<small>e663…a11b</small></span></div><i></i><div className="headhash"><Hash/><span>CHAIN HEAD<small>9d4a…e81c</small></span></div></div></section>}
function Generic({view}:{view:View}){return <section className="panel empty"><div className="empty-icon"><FileCheck2/></div><span className="eyebrow">{view.toUpperCase()}</span><h2>{view==='Review queue'?'Human judgment, clearly assigned':view==='Settings'?'Workspace configuration':'Controlled data intake'}</h2><p>{view==='Review queue'?'Three factual findings are waiting for a named reviewer. Open an exposure from the overview to inspect its evidence trail.':'This showcase keeps all actions local and deterministic. No external provider or live client system is connected.'}</p><button className="secondary">Return to overview</button></section>}
function Intake({close,stage,setStage}:any){return <div className="modal-wrap" role="dialog" aria-modal="true"><button className="modal-scrim" onClick={close}/><div className="modal"><button className="icon close" onClick={close}><X/></button><span className="eyebrow">LOCAL INTAKE / SIMULATED</span><h2>{stage===0?'Add a source batch':stage===1?'Review normalization':'Intake staged'}</h2><p className="intro">Files remain in this local showcase. Nothing is uploaded or sent to an external service.</p>{stage===0?<><div className="drop"><UploadCloud/><b>Drop source files here</b><span>or select CSV, XLSX or PDF · max 25 MB each</span><button className="secondary" onClick={()=>setStage(1)}>Choose demo batch</button></div><div className="modal-note"><ShieldCheck/> Documents are parsed into source facts before deterministic evaluation.</div></>:stage===1?<><div className="file-row"><FileCheck2/><div><b>northstar_aug_2026.csv</b><span>1,248 rows · 184 KB</span></div><span className="tag ok">Ready</span></div><div className="mapping"><span>Employer name <b>employer_name</b></span><span>Deduction date <b>deduction_date</b></span><span>Pay period <b>period_end</b></span></div><button className="primary wide" onClick={()=>setStage(2)}>Stage 1,248 source records</button></>:<div className="success"><Check/><h3>Batch staged successfully</h3><p>Evaluation is ready to run against LAW-2.4.1. This is a deterministic showcase result.</p><button className="primary" onClick={close}>View evaluation register</button></div>}</div></div>}
function Detail({item,close}:any){return <div className="drawer-wrap" role="dialog" aria-modal="true"><button className="modal-scrim" onClick={close}/><aside className="drawer"><button className="icon close" onClick={close}><X/></button><span className="eyebrow">EVALUATION / EVAL-0826-0412</span><h2>{item.employer}</h2><p>{item.period} · LawOS factual determination</p><div className="detail-status"><Clock3/><span><b>{item.status}</b>{item.delta} between configured deadlines</span></div><h3>Source facts</h3><dl><div><dt>Deduction date</dt><dd>{item.deduct}</dd></div><div><dt>Pay period</dt><dd>{item.period}</dd></div><div><dt>Source record</dt><dd>Row 0412</dd></div></dl><h3>Deadline calculations</h3><div className="calc redcalc"><span>BCEA S34A · configured</span><b>{item.bcea}</b><small>Deduction date + 7 calendar days</small></div><div className="calc bluecalc"><span>PFA S13A · configured</span><b>{item.pfa}</b><small>Month end + 7 calendar days</small></div><h3>Provenance</h3><dl><div><dt>Rule version</dt><dd><code>LAW-2.4.1</code></dd></div><div><dt>Input hash</dt><dd><code>sha256:7c6e…a91d</code></dd></div></dl><button className="primary wide"><UserRoundCheck/> Route to reviewer</button><p className="disclaimer">Human review records judgment separately and cannot alter the deterministic calculation.</p></aside></div>}

createRoot(document.getElementById('root')!).render(<App/>);
